apiVersion: v1
kind: Secret
metadata:
  name: users-api-secrets
type: Opaque
stringData:
  RabbitMq__Password: guest
  Jwt__Key: zR8pW5vB9yX2mN4qA7L1jK9sT6uE3hG0fD5cX8vB2nN1mQ4wZ7xR0tY3uI6pP9oL
  UsersConnectionString: Server=sqlserver,1433;Database=FCGUsersDb;User Id=sa;Password=ArquiteturaFiap.NET@2026;TrustServerCertificate=True;
